[functions]
  directory = "netlify/functions"

# Đường dẫn sạch cho API/QR
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/qr"
  to = "/.netlify/functions/qr-get"
  status = 200
